/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tugas.besar.View.Pegawai;

import com.tugas.besar.Controller.Pegawai.KategoriController;
import com.tugas.besar.Model.Pegawai.Kategori;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.tugas.besar.View.Pegawai.ProductView;
import com.tugas.besar.View.Pegawai.KategoriView;
import com.tugas.besar.View.Pegawai.TransaksiView;
import com.tugas.besar.View.Pegawai.RiwayatView;
import com.tugas.besar.View.Pegawai.OperasionalView;


/**
 *
 * @author silvi
 */
public class KategoriView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KategoriView.class.getName());

    /**
     * Creates new form ProductView
     */
    public KategoriView() {
        initComponents();
        loadKategoriTable();
        setTitle("Halaman Kategori");
        setSize(600, 400);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btntambahkategori = new javax.swing.JButton();
        tfnamakategori = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfsimpankategori = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablekategori = new javax.swing.JTable();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnmenukategori = new javax.swing.JButton();
        btnmenuriwayat = new javax.swing.JButton();
        btnmenuproduk = new javax.swing.JButton();
        btnmenutransaksi = new javax.swing.JButton();
        btnmenuoperasional = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugas/besar/Assets/icon.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel2.setText("Daftar Kategori");

        btntambahkategori.setBackground(new java.awt.Color(153, 255, 153));
        btntambahkategori.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btntambahkategori.setForeground(new java.awt.Color(255, 255, 255));
        btntambahkategori.setText("Tambah Kategori");
        btntambahkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahkategoriActionPerformed(evt);
            }
        });

        tfnamakategori.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        tfnamakategori.setText("Masukkan Nama Kategori");
        tfnamakategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamakategoriActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel3.setText("Nama Kategori");

        tfsimpankategori.setBackground(new java.awt.Color(102, 102, 255));
        tfsimpankategori.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        tfsimpankategori.setForeground(new java.awt.Color(255, 255, 255));
        tfsimpankategori.setText("Simpan Kategori");
        tfsimpankategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsimpankategoriActionPerformed(evt);
            }
        });

        tablekategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "Nama Kategori"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablekategori);

        btnedit.setBackground(new java.awt.Color(255, 204, 102));
        btnedit.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Edit Kategori");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 102, 102));
        btnhapus.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("Hapus Kategori");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnmenukategori.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenukategori.setText("Kategori");
        btnmenukategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenukategoriActionPerformed(evt);
            }
        });

        btnmenuriwayat.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenuriwayat.setText("Riwayat");
        btnmenuriwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuriwayatActionPerformed(evt);
            }
        });

        btnmenuproduk.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenuproduk.setText("Produk");
        btnmenuproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuprodukActionPerformed(evt);
            }
        });

        btnmenutransaksi.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenutransaksi.setText("Transaksi");
        btnmenutransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenutransaksiActionPerformed(evt);
            }
        });

        btnmenuoperasional.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenuoperasional.setText("Operasional");
        btnmenuoperasional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuoperasionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmenutransaksi)
                .addGap(18, 18, 18)
                .addComponent(btnmenuproduk)
                .addGap(18, 18, 18)
                .addComponent(btnmenukategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmenuriwayat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmenuoperasional)
                .addGap(11, 11, 11))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmenukategori, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmenuriwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmenuproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmenutransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(btnmenuoperasional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btntambahkategori)
                        .addGap(18, 18, 18)
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfsimpankategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhapus))))
                .addGap(0, 395, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(tfnamakategori, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(464, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntambahkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)))
                .addComponent(tfnamakategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(tfsimpankategori, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1039, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahkategoriActionPerformed
        String namaKategori = tfnamakategori.getText().trim();

        if (namaKategori.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama kategori tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        KategoriController controller = new KategoriController();
        boolean sukses = controller.create(namaKategori);

        if (sukses) {
            JOptionPane.showMessageDialog(this, "Kategori berhasil disimpan.");
            tfnamakategori.setText(""); // Kosongkan field
            loadKategoriTable(); // Refresh isi tabel
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan kategori.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btntambahkategoriActionPerformed

    private void tfnamakategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamakategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamakategoriActionPerformed

    private void tfsimpankategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsimpankategoriActionPerformed
        
    }//GEN-LAST:event_tfsimpankategoriActionPerformed

    
    
    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
       int selectedRow = tablekategori.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin dihapus terlebih dahulu.");
        return;
    }

    String nama = tablekategori.getValueAt(selectedRow, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data \"" + nama + "\"?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // Koneksi ke database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mugi_berkah", "root", "");

            // Ambil ID dari tabel
            int id = Integer.parseInt(tablekategori.getValueAt(selectedRow, 0).toString());

            // Query DELETE
            String sql = "DELETE FROM produk WHERE id=?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, id);

            // Inilah bagian yang sebelumnya hilang
            int affected = stmt.executeUpdate();

            if (affected > 0) {
                // Jika berhasil dihapus dari DB, baru hapus dari GUI
                DefaultTableModel model = (DefaultTableModel) tablekategori.getModel();
                model.removeRow(selectedRow);

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus dari database.");
            }

            stmt.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnmenutransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenutransaksiActionPerformed
    TransaksiView transaksiFrame = new TransaksiView();
    transaksiFrame.setVisible(true);
    transaksiFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenutransaksiActionPerformed

    private void btnmenuprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuprodukActionPerformed
    ProductView productFrame = new ProductView();
    productFrame.setVisible(true);
    productFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenuprodukActionPerformed

    private void btnmenukategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenukategoriActionPerformed
    KategoriView kategoriFrame = new KategoriView();
    kategoriFrame.setVisible(true);
    kategoriFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenukategoriActionPerformed

    private void btnmenuriwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuriwayatActionPerformed
    RiwayatView riwayatFrame = new RiwayatView();
    riwayatFrame.setVisible(true);
    riwayatFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenuriwayatActionPerformed

    private void btnmenuoperasionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuoperasionalActionPerformed
    OperasionalView operasionalFrame = new OperasionalView();
    operasionalFrame.setVisible(true);
    operasionalFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenuoperasionalActionPerformed
    private void loadKategoriTable() {
        KategoriController controller = new KategoriController();
        List<Kategori> daftarKategori = controller.read();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama");
        
        int no = 1;
        for (Kategori kategori : daftarKategori) {
            model.addRow(new Object[]{
                no++,
                kategori.getNama(),
              
            });
        }

        tablekategori.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KategoriView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnmenukategori;
    private javax.swing.JButton btnmenuoperasional;
    private javax.swing.JButton btnmenuproduk;
    private javax.swing.JButton btnmenuriwayat;
    private javax.swing.JButton btnmenutransaksi;
    private javax.swing.JButton btntambahkategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablekategori;
    private javax.swing.JTextField tfnamakategori;
    private javax.swing.JTextField tfsimpankategori;
    // End of variables declaration//GEN-END:variables
}
