/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tugas.besar.View.Pegawai;


import com.tugas.besar.Controller.Pegawai.OperasionalController;
import com.tugas.besar.DataAccesObject.Pegawai.OperasionalDAO;
import com.tugas.besar.Model.Pegawai.Operasional;
import com.tugas.besar.View.Pegawai.ProductView;
import com.tugas.besar.View.Pegawai.KategoriView;
import com.tugas.besar.View.Pegawai.TransaksiView;
import com.tugas.besar.View.Pegawai.RiwayatView;
import com.tugas.besar.View.Pegawai.OperasionalView;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author silvi
 */
public class OperasionalView extends javax.swing.JFrame {
    private int id;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OperasionalView.class.getName());

    /**
     * Creates new form ProductView
     */
    public OperasionalView() {
        initComponents();
        loadTableOperasional();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane28 = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        btntambahoperasional13 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableoperasional = new javax.swing.JTable();
        tfnamaoperasional = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        tfharga = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        btnhapus13 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnmenukategori = new javax.swing.JButton();
        btnmenuriwayat = new javax.swing.JButton();
        btnmenuproduk = new javax.swing.JButton();
        btnmenutransaksi = new javax.swing.JButton();
        btnmenuoperasional = new javax.swing.JButton();
        setText = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugas/besar/Assets/icon.png"))); // NOI18N
        jLabel53.setText("jLabel1");

        jLabel54.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel54.setText("Daftar Operasional");

        btntambahoperasional13.setBackground(new java.awt.Color(153, 255, 153));
        btntambahoperasional13.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btntambahoperasional13.setForeground(new java.awt.Color(255, 255, 255));
        btntambahoperasional13.setText("Tambah Operasional");
        btntambahoperasional13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahoperasional13ActionPerformed(evt);
            }
        });

        tableoperasional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableoperasional);

        tfnamaoperasional.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        tfnamaoperasional.setText("Masukkan Nama Barang");

        jLabel55.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel55.setText("Nama Barang");

        jLabel56.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel56.setText("Harga");

        tfharga.setText("Masukkan Harga");

        btnedit.setBackground(new java.awt.Color(255, 204, 102));
        btnedit.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Edit Operasional");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus13.setBackground(new java.awt.Color(255, 102, 102));
        btnhapus13.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnhapus13.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus13.setText("Hapus Operasional");
        btnhapus13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapus13ActionPerformed(evt);
            }
        });

        btnmenukategori.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenukategori.setText("Kategori");
        btnmenukategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenukategoriActionPerformed(evt);
            }
        });

        btnmenuriwayat.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenuriwayat.setText("Riwayat");
        btnmenuriwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuriwayatActionPerformed(evt);
            }
        });

        btnmenuproduk.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenuproduk.setText("Produk");
        btnmenuproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuprodukActionPerformed(evt);
            }
        });

        btnmenutransaksi.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenutransaksi.setText("Transaksi");
        btnmenutransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenutransaksiActionPerformed(evt);
            }
        });

        btnmenuoperasional.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenuoperasional.setText("Operasional");
        btnmenuoperasional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuoperasionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmenutransaksi)
                .addGap(18, 18, 18)
                .addComponent(btnmenuproduk)
                .addGap(18, 18, 18)
                .addComponent(btnmenukategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmenuriwayat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmenuoperasional)
                .addGap(11, 11, 11))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmenukategori, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmenuriwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmenuproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmenutransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnmenuoperasional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        setText.setText("Set Text");
        setText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55)
                            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel15Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(tfharga, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel56))
                                .addGroup(jPanel15Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(tfnamaoperasional, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 112, Short.MAX_VALUE))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(btntambahoperasional13)
                        .addGap(18, 18, 18)
                        .addComponent(btnedit)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setText)
                            .addComponent(btnhapus13))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnhapus13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btntambahoperasional13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfnamaoperasional, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfharga, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setText))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jScrollPane28.setViewportView(jPanel15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane28, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmenutransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenutransaksiActionPerformed
    TransaksiView transaksiFrame = new TransaksiView();
    transaksiFrame.setVisible(true);
    transaksiFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenutransaksiActionPerformed

    private void btnmenuprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuprodukActionPerformed
    ProductView productFrame = new ProductView();
    productFrame.setVisible(true);
    productFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenuprodukActionPerformed

    private void btnmenukategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenukategoriActionPerformed
    KategoriView kategoriFrame = new KategoriView();
    kategoriFrame.setVisible(true);
    kategoriFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenukategoriActionPerformed

    private void btnmenuriwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuriwayatActionPerformed
    RiwayatView riwayatFrame = new RiwayatView();
    riwayatFrame.setVisible(true);
    riwayatFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenuriwayatActionPerformed

    private void btnmenuoperasionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuoperasionalActionPerformed
    OperasionalView operasionalFrame = new OperasionalView();
    operasionalFrame.setVisible(true);
    operasionalFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenuoperasionalActionPerformed

    private void btntambahoperasional13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahoperasional13ActionPerformed
        String namaOperasional = tfnamaoperasional.getText().trim();
        String hargaOperasional = tfharga.getText().trim();
        
        if (namaOperasional.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Operasional tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        if (hargaOperasional.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harga Operasional tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int hargaToInt;
        try {
            hargaToInt = Integer.parseInt(hargaOperasional);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
      
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin melanjutkan? \"" +  "\"?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                 OperasionalController controller = new OperasionalController();
                  boolean sukses = controller.create(namaOperasional, hargaToInt);

                if (!sukses){
                    JOptionPane.showMessageDialog(this, "Gagal menambahkan Operasional", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                JOptionPane.showMessageDialog(this, "Operasional berhasil di tambahkan.");
                tfnamaoperasional.setText(""); 
                tfharga.setText("");
                loadTableOperasional(); 

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data: " + e.getMessage());
            }
        }
       
    }//GEN-LAST:event_btntambahoperasional13ActionPerformed

    
    private void setTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTextActionPerformed
        TableModel model = tableoperasional.getModel();
        int[] selectedRows = tableoperasional.getSelectedRows();

        if (selectedRows.length > 0) {
            int row = selectedRows[0];

            Operasional nama = (Operasional) model.getValueAt(row, 1);
            String harga = model.getValueAt(row, 2).toString();
            

            tfnamaoperasional.setText(nama.getNama());
            tfharga.setText(harga);
            
            this.id = nama.getId();

            
        }
    }//GEN-LAST:event_setTextActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        String namaOperasional = tfnamaoperasional.getText().trim();
        String hargaOperasional = tfharga.getText().trim();
        
        if (namaOperasional.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Operasional tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        if (hargaOperasional.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harga Operasional tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int hargaToInt;
        try {
            hargaToInt = Integer.parseInt(hargaOperasional);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
      
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin mengubah data? \"" + "\"?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                 OperasionalController controller = new OperasionalController();
                  boolean sukses = controller.update(this.id,namaOperasional, hargaToInt);

                if (!sukses){
                    JOptionPane.showMessageDialog(this, "Gagal mengupdate Operasional", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                JOptionPane.showMessageDialog(this, "Operasional berhasil di update.");
                tfnamaoperasional.setText(""); 
                tfharga.setText("");
                loadTableOperasional(); 

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapus13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapus13ActionPerformed
        

        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus? \"" +  "\"?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                 OperasionalController controller = new OperasionalController();
                  boolean sukses = controller.delete(this.id);

                if (!sukses){
                    JOptionPane.showMessageDialog(this, "Gagal menghapus Operasional", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                JOptionPane.showMessageDialog(this, "Operasional berhasil di hapus.");
                tfnamaoperasional.setText(""); 
                tfharga.setText("");
                loadTableOperasional(); 

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnhapus13ActionPerformed
    
    private void loadTableOperasional() {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableoperasional.setModel(tableModel);

        
        tableModel.addColumn("No");
        tableModel.addColumn("Nama");
        tableModel.addColumn("Harga");
        
       
        tableModel.setRowCount(0);

        OperasionalController controller = new OperasionalController();
        
        
        List<Operasional> daftarOperasional = controller.read();
        int no = 1;
        for (Operasional operasional : daftarOperasional) {
            Object[] baris = {
//                produk.getId(),
                no++,
                operasional,
                operasional.getHarga(),
                
                
            };
            tableModel.addRow(baris);
        }
          tableoperasional.setFillsViewportHeight(true);      
          
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OperasionalView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus13;
    private javax.swing.JButton btnmenukategori;
    private javax.swing.JButton btnmenuoperasional;
    private javax.swing.JButton btnmenuproduk;
    private javax.swing.JButton btnmenuriwayat;
    private javax.swing.JButton btnmenutransaksi;
    private javax.swing.JButton btntambahoperasional13;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JButton setText;
    private javax.swing.JTable tableoperasional;
    private javax.swing.JTextField tfharga;
    private javax.swing.JTextField tfnamaoperasional;
    // End of variables declaration//GEN-END:variables
}
