/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tugas.besar.View.Pegawai;
import com.tugas.besar.Controller.Pegawai.ProductController;
import com.tugas.besar.Controller.Pegawai.TransaksiController;
import com.tugas.besar.DataAccesObject.Pegawai.ProductDAO;
import com.tugas.besar.Model.Pegawai.Kategori;
import com.tugas.besar.Model.Pegawai.Keranjang;
import com.tugas.besar.Model.Pegawai.Product;
import com.tugas.besar.View.Pegawai.ProductView;
import com.tugas.besar.View.Pegawai.KategoriView;
import com.tugas.besar.View.Pegawai.TransaksiView;
import com.tugas.besar.View.Pegawai.RiwayatView;
import com.tugas.besar.View.Pegawai.OperasionalView;
import static java.lang.Integer.parseInt;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author silvi
 */
public class TransaksiView extends javax.swing.JFrame {
    private int id;
    ArrayList<Keranjang> keranjangDisplay = new ArrayList<Keranjang>();
    String metodePembayaran;
    int totalHarga;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransaksiView.class.getName());

    /**
     * Creates new form TransaksiView
     */
    public TransaksiView() {
        initComponents();
        labelUangDiterima.setVisible(false);
        tfUangDiterima.setVisible(false);
        labelKembalian.setVisible(false);
        tfKembalian.setVisible(false);

//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        loadTableMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        tftotalharga = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfuangditerima = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfnamamakanan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfharga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfKembalian = new javax.swing.JTextField();
        btnpesan = new javax.swing.JButton();
        tfnamapelanggan = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btntunai = new javax.swing.JButton();
        btnqris = new javax.swing.JButton();
        labelUangDiterima = new javax.swing.JLabel();
        tfUangDiterima = new javax.swing.JTextField();
        labelKembalian = new javax.swing.JLabel();
        tfjumlahPesanan = new javax.swing.JTextField();
        btnProsesPembayaran = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableKeranjang = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnmenukategori2 = new javax.swing.JButton();
        btnmenuriwayat2 = new javax.swing.JButton();
        btnmenuproduk2 = new javax.swing.JButton();
        btnmenutransaksi2 = new javax.swing.JButton();
        btnmenuoperasional2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblmenu = new javax.swing.JTable();
        btntambahpesanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tugas/besar/Assets/icon.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel2.setText("Daftar Menu");

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel23.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel23.setText("Total");

        tftotalharga.setEditable(false);
        tftotalharga.setText("Rp. 000.000");
        tftotalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftotalhargaActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel25.setText("Jumlah Uang Diterima");

        tfuangditerima.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        tfuangditerima.setText("Masukkan Uang Diterima");
        tfuangditerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuangditerimaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel3.setText("Nama Makanan");

        tfnamamakanan.setEditable(false);
        tfnamamakanan.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel4.setText("Harga");

        tfharga.setEditable(false);
        tfharga.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah Pesanan");

        tfKembalian.setEditable(false);
        tfKembalian.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        tfKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKembalianActionPerformed(evt);
            }
        });

        btnpesan.setText("Tambahkan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        tfnamapelanggan.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        tfnamapelanggan.setText("Masukkan Nama Pembeli");

        jLabel26.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel26.setText("Atas Nama");

        jLabel24.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel24.setText("Metode Pembayaran");

        btntunai.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        btntunai.setText("Tunai");
        btntunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntunaiActionPerformed(evt);
            }
        });

        btnqris.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        btnqris.setText("QRIS");

        labelUangDiterima.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        labelUangDiterima.setText("Jumlah Uang Diterima");

        tfUangDiterima.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        tfUangDiterima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUangDiterimaActionPerformed(evt);
            }
        });

        labelKembalian.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        labelKembalian.setText("Kembalian");

        tfjumlahPesanan.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        tfjumlahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfjumlahPesananActionPerformed(evt);
            }
        });

        btnProsesPembayaran.setText("Proses Pembayaran");
        btnProsesPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesPembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfnamamakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(tfharga, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(55, 55, 55)
                                .addComponent(tfUangDiterima, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnProsesPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(98, 98, 98)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel26)
                                        .addComponent(tfnamapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelUangDiterima, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(btntunai)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnqris)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(labelKembalian)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tfKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnpesan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(tfjumlahPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(815, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProsesPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnamamakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnamapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfharga, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntunai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnqris, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUangDiterima))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUangDiterima, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelKembalian)
                            .addComponent(tfKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(btnpesan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(264, Short.MAX_VALUE)
                    .addComponent(tfjumlahPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(186, 186, 186)))
        );

        tableKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama Makanan", "Harga", "Jumlah Makanan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableKeranjang);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(tfuangditerima, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 737, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(tftotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 533, Short.MAX_VALUE)
                .addComponent(tfuangditerima, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel25)
                .addGap(256, 256, 256))
        );

        btnmenukategori2.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenukategori2.setText("Kategori");
        btnmenukategori2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenukategori2ActionPerformed(evt);
            }
        });

        btnmenuriwayat2.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenuriwayat2.setText("Riwayat");
        btnmenuriwayat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuriwayat2ActionPerformed(evt);
            }
        });

        btnmenuproduk2.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenuproduk2.setText("Produk");
        btnmenuproduk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuproduk2ActionPerformed(evt);
            }
        });

        btnmenutransaksi2.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenutransaksi2.setText("Transaksi");
        btnmenutransaksi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenutransaksi2ActionPerformed(evt);
            }
        });

        btnmenuoperasional2.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnmenuoperasional2.setText("Operasional");
        btnmenuoperasional2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuoperasional2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmenutransaksi2)
                .addGap(18, 18, 18)
                .addComponent(btnmenuproduk2)
                .addGap(18, 18, 18)
                .addComponent(btnmenukategori2)
                .addGap(18, 18, 18)
                .addComponent(btnmenuriwayat2)
                .addGap(18, 18, 18)
                .addComponent(btnmenuoperasional2)
                .addGap(7, 7, 7))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmenukategori2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmenuproduk2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmenutransaksi2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnmenuoperasional2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnmenuriwayat2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tblmenu.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        tblmenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama Makanan", "Kategori", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblmenu);

        btntambahpesanan.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        btntambahpesanan.setText("Tambah Pesanan");
        btntambahpesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahpesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(665, Short.MAX_VALUE)
                        .addComponent(btntambahpesanan)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(527, 527, 527))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addComponent(btntambahpesanan)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1084, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmenutransaksi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenutransaksi2ActionPerformed
    TransaksiView transaksiFrame = new TransaksiView();
    transaksiFrame.setVisible(true);
    transaksiFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenutransaksi2ActionPerformed

    private void btnmenuproduk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuproduk2ActionPerformed
    ProductView productFrame = new ProductView();
    productFrame.setVisible(true);
    productFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenuproduk2ActionPerformed

    private void btnmenukategori2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenukategori2ActionPerformed
    KategoriView kategoriFrame = new KategoriView();
    kategoriFrame.setVisible(true);
    kategoriFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenukategori2ActionPerformed

    private void btnmenuriwayat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuriwayat2ActionPerformed
    RiwayatView riwayatFrame = new RiwayatView();
    riwayatFrame.setVisible(true);
    riwayatFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenuriwayat2ActionPerformed

    private void btnmenuoperasional2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuoperasional2ActionPerformed
    OperasionalView operasionalFrame = new OperasionalView();
    operasionalFrame.setVisible(true);
    operasionalFrame.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnmenuoperasional2ActionPerformed

    private void tfuangditerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuangditerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuangditerimaActionPerformed

    private void tftotalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftotalhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftotalhargaActionPerformed

    private void btntambahpesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahpesananActionPerformed
        TableModel model = tblmenu.getModel();
        int[] selectedRows = tblmenu.getSelectedRows();

        if (selectedRows.length > 0) {
            int row = selectedRows[0];

            Product produk = (Product) model.getValueAt(row, 1);
            String harga = model.getValueAt(row, 3).toString();

            tfnamamakanan.setText(produk.getNama());
            tfharga.setText(harga);
            this.id = produk.getId();
            int hargaToInt = Integer.parseInt(harga);
//            Keranjang newKeranjang;
//            keranjangDisplay.add(newKeranjang = new Keranjang(produk.getNama(),hargaToInt)); 
            
            

//            this.kategoriId = produk.getKategoriId(); 

           
        }
    }//GEN-LAST:event_btntambahpesananActionPerformed
    
    private void btnPesanToTable(List<Keranjang> daftarPesanan){
        DefaultTableModel tableModel = new DefaultTableModel();
        tableKeranjang.setModel(tableModel);

        
        tableModel.addColumn("No");
        tableModel.addColumn("Nama Makanan");
        tableModel.addColumn("Harga");
        tableModel.addColumn("Jumlah Makanan");
        
       
        tableModel.setRowCount(0);

        int no = 1;
        for (Keranjang pesanan : daftarPesanan) {
            Object[] baris = {
                no++,
                pesanan.getNamaMakanan(),
                pesanan.getHargaMakanan(),
                pesanan.getJumlahPesanan(),
                
            };
            tableModel.addRow(baris);
        }
        tblmenu.setFillsViewportHeight(true);
    }
    
    private void hitungTotalHarga() {
        int total = 0;
        for (Keranjang item : keranjangDisplay) {
            total += item.getHargaMakanan() * item.getJumlahPesanan();
        }
        NumberFormat formatter = NumberFormat.getNumberInstance(new Locale("id", "ID"));
        tftotalharga.setText(formatter.format(total));
        this.totalHarga = total;

    }
    
    
    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        
        String namaMakanan = tfnamamakanan.getText();
        String hargaMakanan = tfharga.getText();
        String jumlahPesanan = tfjumlahPesanan.getText();

        if (namaMakanan.isEmpty() || hargaMakanan.isEmpty() || jumlahPesanan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua data harus diisi.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int hargaMakananToInt;
        int jumlahPesananToInt;

        try {
            hargaMakananToInt = Integer.parseInt(hargaMakanan);
            jumlahPesananToInt = Integer.parseInt(jumlahPesanan);

            if (jumlahPesananToInt <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah pesanan harus lebih dari 0.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Harga dan jumlah harus berupa angka.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

     
        boolean found = false;
        for (Keranjang k : keranjangDisplay) {
            if (k.getNamaMakanan().equalsIgnoreCase(namaMakanan)) {
                JOptionPane.showMessageDialog(this, "Nama makanan sudah ada di keranjang.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        if (!found) {
           
            keranjangDisplay.add(new Keranjang(namaMakanan, hargaMakananToInt, jumlahPesananToInt));
        }

      
        btnPesanToTable(keranjangDisplay);
        
        hitungTotalHarga();
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnpesanActionPerformed

    private void tfKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKembalianActionPerformed

    private void btntunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntunaiActionPerformed
        labelUangDiterima.setVisible(true);
        tfUangDiterima.setVisible(true);
        labelKembalian.setVisible(true);
        tfKembalian.setVisible(true);
    }//GEN-LAST:event_btntunaiActionPerformed

    private void btnProsesPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesPembayaranActionPerformed
        String namaPelanggan = tfnamapelanggan.getText();
//        String totalHarga = tftotalharga.getText();
       
        this.metodePembayaran = "cash";
        
        
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin melanjutkan?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                TransaksiController controller = new TransaksiController();
                Integer idTransaksi = controller.create(namaPelanggan, totalHarga, metodePembayaran);

                if (idTransaksi == null) {
                    JOptionPane.showMessageDialog(this, "Transaksi Gagal", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                

                JOptionPane.showMessageDialog(this, "Transaksi berhasil");
                
                keranjangDisplay.clear();                       
                btnPesanToTable(keranjangDisplay); 
                tfnamamakanan.setText("");
                tfharga.setText("");
                tfjumlahPesanan.setText("");
                tfnamapelanggan.setText("");                    
                tftotalharga.setText("");                        
                tfUangDiterima.setText("");                      
                tfKembalian.setText("");   

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data: " + e.getMessage());
            }
        }
        
        
        
        
    }//GEN-LAST:event_btnProsesPembayaranActionPerformed

    private void tfUangDiterimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUangDiterimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUangDiterimaActionPerformed

    private void tfjumlahPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfjumlahPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfjumlahPesananActionPerformed
    
    private void loadTableMenu(){
    
    
        DefaultTableModel tableModel = new DefaultTableModel();
        tblmenu.setModel(tableModel);

        
        tableModel.addColumn("No");
        tableModel.addColumn("Nama Makanan");
        tableModel.addColumn("Kategori");
        tableModel.addColumn("Harga");
        
       
        tableModel.setRowCount(0);

        ProductController controller = new ProductController();
        
        
        List<Product> daftarProduk = controller.read();
        ProductDAO getKategori  = new ProductDAO();
        int no = 1;
        for (Product produk : daftarProduk) {
            Object[] baris = {
//                produk.getId(),
                no++,
                produk,
                getKategori.getKategoriById(produk.getKategoriId()),
                produk.getHarga(),
                
            };
            tableModel.addRow(baris);
        }
          tblmenu.setFillsViewportHeight(true);
    
    
    
    
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransaksiView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProsesPembayaran;
    private javax.swing.JButton btnmenukategori2;
    private javax.swing.JButton btnmenuoperasional2;
    private javax.swing.JButton btnmenuproduk2;
    private javax.swing.JButton btnmenuriwayat2;
    private javax.swing.JButton btnmenutransaksi2;
    private javax.swing.JButton btnpesan;
    private javax.swing.JButton btnqris;
    private javax.swing.JButton btntambahpesanan;
    private javax.swing.JButton btntunai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelKembalian;
    private javax.swing.JLabel labelUangDiterima;
    private javax.swing.JTable tableKeranjang;
    private javax.swing.JTable tblmenu;
    private javax.swing.JTextField tfKembalian;
    private javax.swing.JTextField tfUangDiterima;
    private javax.swing.JTextField tfharga;
    private javax.swing.JTextField tfjumlahPesanan;
    private javax.swing.JTextField tfnamamakanan;
    private javax.swing.JTextField tfnamapelanggan;
    private javax.swing.JTextField tftotalharga;
    private javax.swing.JTextField tfuangditerima;
    // End of variables declaration//GEN-END:variables
}